### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jyap808** [HashEngineering/myriadcoin-wallet#1]
I get this error when trying to build. 

I run this version of Maven.  Do you run an older version?: 
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T07:37:52-10:00)

ERROR:
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.7.0:generate-sources (default-generate-sources) on project wallet: Execution default-generate-sources of goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.7.0:generate-sources failed: A required class was missing while executing com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.7.0:generate-sources: Lorg/sonatype/aether/RepositorySystem;

**Comment by HashEngineering** [comment]
I currently use an IDE to compile the app.  I will try maven (3.0.5) and see what happens.

**Comment by jyap808** [comment]
Thanks. Bitcoinj and Bitcoin Android wallet compile with no issues using my version of Maven (latest)

**Comment by HashEngineering** [comment]
Compiling works with maven 3.0.5 using -DskipTests=true (since the unit tests have a lot of bitcoin related items) and most of the unit tests will fail.

**Comment by jyap808** [comment]
Ah, yeah I had to use that flag when I built myriadcoinj. I will try that...  Then try downgrading to maven 3.0.

You might want to try upgrading to a newer Maven. ;)

Thanks for testing.

**Comment by HashEngineering** [comment]
I will try with the updated version of maven.  Perhaps org.sonatype.aether.RepositorySystem is a missing dependency? or there is a bug in the POM file?  Hope to find out soon.

**Comment by jyap808** [comment]
Here is what I wrote as a note last night when I jumped on Google:

Issue: https://code.google.com/p/appengine-maven-plugin/issues/detail?id=31
FIX?: https://code.google.com/p/maven-android-plugin/issues/detail?id=395
