### ISSUE TITLE
Coins not received in wallet

### ISSUE THREAD

**Issue by jwinterm** [HashEngineering/myriadcoin-wallet#3]
I sent a tx from an exchange to my wallet address:
https://cryptap.us/myr/explorer/address/MHYHyseriwbb67odYk3omAtKS8acbbNtmc

The coins show up on the block explorer, but I have a zero balance in my wallet. The address is definitely correct. If I go to network status tab it shows the same block height as the explorer.

**Comment by jwinterm** [comment]
Nevermind, reset blockchain and coins were received.

**Comment by HashEngineering** [comment]
Great.  Resetting the blockchain is the correct way to resolve this issue.
